name: Build and Push Docker Image

on:
  release:
    types: [published]

env:
  IMAGE_TAG: ${{ github.event.release.tag_name }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Run Maven Build
      run: |
        pushd mdb-spring-boot
        mvn clean install -DskipTests
        popd

    - name: Run NPM Build
      run: |
        pushd ui
        npm install
        npm run build
        popd

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: softprobe
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push docker images
      run: |
        pushd mdb-spring-boot
        docker build -t softprobe/demo-mongodb-spring-boot:${{ github.event.release.tag_name }} .
        docker push softprobe/demo-mongodb-spring-boot:${{ github.event.release.tag_name }}
        popd

    - name: Build and push docker images
      run: |
        pushd ui
        docker build -t softprobe/demo-mongodb-ui:${{ github.event.release.tag_name }} .
        docker push softprobe/demo-mongodb-ui:${{ github.event.release.tag_name }}
        popd
